### ISSUE TITLE
File downloads twice in example

### ISSUE THREAD

**Issue by hayatnoor** [ytb2mp3/youtube-mp3-downloader#39]
In your example1.js which leverages downloader.js, I find that the file downloads twice... once with a proper filename specified in the getMP3 function and another file "Funk" gets put in the root directory of the project. Any ideas?

**Comment by MarlonS91** [comment]
I am having the same issue. It appears that `fluent-ffmpeg` handles the task of saving the output file; but I don't see what seems to be causing this issue. Interestingly enough, my filenames are formatted `{videId}.mp3`; the improper filename appears to come from the last word of the video title.

**Update**: The issue is in fact due to `fluent-ffmpeg`. Specifically, the culprit is the output options to write metadata (snippet inserted below). See reference [[1]](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/502#issuecomment-196709174) and [[2]](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/311#issuecomment-54281059) for more information.

https://github.com/ytb2mp3/youtube-mp3-downloader/blob/90582944811d384e081aca5dda8744c1146d01a3/lib/YoutubeMp3Downloader.js#L142-L146

**Comment by nikkilr88** [comment]
I'm having the same problem. Has anyone found a fix?

**Comment by ytb2mp3** [comment]
A bugfix was just published to npm, with version `0.6.6`. Thanks for your patience!
